version: '3.9'

services:
  db:
    container_name: gift-crowdfunding-postgres
    image: postgres:14.3-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata

  app:
    container_name: gift-crowdfunding-app
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    environment:
      # map env vars from .env file
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - BASE_PATH=${BASE_PATH}

volumes:
  pgdata:
